apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-indexer-gateway"
  labels:
    subsquid.io/component: indexer-gateway
    subsquid.io/release: "{{ .Release.Name }}"
spec:
  selector:
    subsquid.io/component: indexer-gateway
    subsquid.io/release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 4010
      targetPort: 8080
