apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-indexer"
  labels:
    subsquid.io/component: indexer
    subsquid.io/release: "{{ .Release.Name }}"
spec:
  selector:
    subsquid.io/component: indexer
    subsquid.io/release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
