apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    subsquid.io/component: redis
    subsquid.io/release: "{{ .Release.Name }}"
spec:
  selector:
    subsquid.io/component: redis
    subsquid.io/release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
