squid:
  db:
    image: postgres:12
  indexer:
    image: subsquid/hydra-evm-indexer:5
    forceHeight: "true"
    blockHeight: "0"
  indexerGateway:
    image: subsquid/hydra-evm-indexer-gateway:5
  indexerStatusService:
    image: subsquid/hydra-indexer-status-service:5
  redis:
    image: redis:6.0-alpine
  provider:
    endpoint: wss://wss.api.moonbeam.network
