apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-db-pvc"
  labels:
    subsquid.io/component: db-pvc
    subsquid.io/release: "{{ .Release.Name }}"
  annotations:
    subsquid.io/version: 0.2.0-alpha2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
