apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-db-pv"
  labels:
    subsquid.io/component: db-pv
    subsquid.io/release: "{{ .Release.Name }}"
  annotations:
    subsquid.io/version: 0.2.0-alpha2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
