apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-indexer-status-service"
  labels:
    subsquid.io/component: indexer-status-service
    subsquid.io/release: "{{ .Release.Name }}"
spec:
  selector:
    subsquid.io/component: indexer-status-service
    subsquid.io/release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
